server:
  servlet:
    contextPath: "/catalog"
  port: ${http.port:9000}

service:
  name: dms-catalog

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true